CREATE DATABASE Brainstorming;

USE Brainstorming;

CREATE TABLE clientes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    complemento VARCHAR(255),
    cidade VARCHAR(255) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    estado VARCHAR(255) NOT NULL
);
